language: node_js

node_js:
- "11"

os: osx

branches:
  only:
  - master

sudo: required

script: bash build.sh

deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    local-dir: "out"
    skip_cleanup: true
    on:
      branch: master